### ISSUE TITLE
批量扫描回显问题

### ISSUE THREAD

**Issue by ghost** [HatBoy/Struts2-Scan#3]
批量的时候回显是不是线程冲突，有并列的有没颜色的
`[*] ----------------results------------------
[+] 正在扫描URL:http://xxx.cn
[*] ----------------results------------------[+] 正在扫描URL:http://ssxxx.com

[+] 正在扫描URL:http://xxx.cn
[*] ----------------results------------------
[+] 正在扫描URL:http://m.cn
`

**Comment by HatBoy** [comment]
确实存在该问题，不影响使用，无需进行修复
